spring:
  application:
    name: autoservice-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/mechano?currentSchema=public
    username: mechanoDB
    password: ${MECHANO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

mechano:
  media:
    base-dir: ./data/media
    max-upload-bytes: 5242880 # 5MB

    image:
      max-width: 1600
      max-height: 1600
      thumb-size: 300
      quality: 0.82